name: Deploy to Development

on:
  push:
    branches:
      - dev

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.9

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        client-id: ${{ secrets.ARM_CLIENT_ID }}
        tenant-id: ${{ secrets.ARM_TENANT_ID }}
        subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        allow-no-subscriptions: true

    - name: Terraform Init
      run: terraform init
      working-directory: ./dev  # Adjust to your directory

    - name: List Terraform State
      run: |
        terraform state list || echo "No state found"
      working-directory: ./dev  # Adjust to your directory

    - name: Check for Existing Resources
      id: check_resources
      run: |
        terraform state list > state_list.txt || touch state_list.txt
        cat state_list.txt
        grep 'module.network.azurerm_virtual_network.main' state_list.txt || echo "missing" >> missing_resources.txt
        grep 'module.network.azurerm_network_security_group.main' state_list.txt || echo "missing" >> missing_resources.txt
        grep 'module.backend_compute.azurerm_public_ip.public_ip' state_list.txt || echo "missing" >> missing_resources.txt
        grep 'module.cms_compute.azurerm_public_ip.public_ip' state_list.txt || echo "missing" >> missing_resources.txt
        grep 'module.frontend_compute.azurerm_public_ip.public_ip' state_list.txt || echo "missing" >> missing_resources.txt
        grep 'module.backend_compute.azurerm_virtual_machine.vm' state_list.txt || echo "missing" >> missing_resources.txt
        grep 'module.cms_compute.azurerm_virtual_machine.vm' state_list.txt || echo "missing" >> missing_resources.txt
        grep 'module.frontend_compute.azurerm_virtual_machine.vm' state_list.txt || echo "missing" >> missing_resources.txt
        if [ -f missing_resources.txt ]; then
          echo "missing=true" >> $GITHUB_ENV
        else
          echo "missing=false" >> $GITHUB_ENV
        fi
      working-directory: ./dev  # Adjust to your directory

    - name: Trigger Import Workflow
      if: env.missing == 'true'
      uses: actions/github-script@v3
      with:
        script: |
          github.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'import-resources-dev.yml',
            ref: 'dev'
          })

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./dev  # Adjust to your directory
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        TF_VAR_admin_username: ${{ secrets.TF_VAR_admin_username }}
        TF_VAR_admin_password: ${{ secrets.TF_VAR_admin_password }}